import type { Metadata } from "next";
import "./globals.css";
import RootProvider from "@/Providers/RootProvider/Providers";

export const metadata: Metadata = {
  title: "TekzoBD Offline Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
